# Generated by Django 4.2.2 on 2023-07-20 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0001_initial'),
        ('store', '0001_initial'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='vendor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='orders',
                to='vendors.vendor',
                verbose_name='Продавец',
            ),
        ),
        migrations.AddField(
            model_name='productinbasket',
            name='basket',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='products_in_basket', to='orders.basket'
            ),
        ),
        migrations.AddField(
            model_name='productinbasket',
            name='offer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='in_baskets', to='store.offervendor'
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
