# Generated by Django 4.0 on 2022-01-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='money_in_wallet',
            field=models.IntegerField(default=0),
        ),
    ]
