# Generated by Django 4.0.2 on 2022-03-18 08:01

from django.db import migrations, models
import store.models.brand
import store.models.product
import store.models.vendor


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=store.models.brand.logo_store_path, verbose_name='Логотип')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfferVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('verify', 'Подтверждение'), ('payment', 'Оплата'), ('delivery', 'Доставка'), ('completed', 'Выполнен'), ('cancel', 'Отменен')], default='verify', max_length=16)),
                ('payment', models.CharField(choices=[('cash', 'Наличными'), ('wallet', 'Кошелек'), ('online', 'online')], max_length=16)),
                ('delivery', models.CharField(choices=[('pickup', 'Самовывоз'), ('courier', 'Курьером')], max_length=16)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_deliver', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_cancel', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoReviewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=store.models.product.reviews_image_path, verbose_name=' Фотограция')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128, verbose_name='Модель')),
                ('production', models.IntegerField(default=2020)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('deep', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('color', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=store.models.product.image_store_path, verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptOfPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Наличными'), ('wallet', 'Кошелек'), ('online', 'online')], max_length=16)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('detail', models.CharField(default='', max_length=256)),
                ('is_canceled', models.BooleanField(default=False)),
                ('create_data', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Рейтинг')),
                ('review_text', models.TextField(verbose_name='Отзыв')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок отзыва')),
                ('plus', models.TextField(verbose_name='Достоинства')),
                ('minus', models.TextField(verbose_name='Недостатки')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('moderation', models.BooleanField(default=False, verbose_name='Прошел модерацию')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Рейтинг')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('moderation', models.BooleanField(default=False, verbose_name='Прешел модерацию')),
                ('create_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=store.models.vendor.vendor_store_path, verbose_name='Логотип')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='sug')),
            ],
        ),
    ]
