# Generated by Django 3.2.9 on 2021-12-18 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import store.models.brand
import store.models.product
import store.models.vendor


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=store.models.brand.logo_store_path, verbose_name='Логотип')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category', verbose_name='Родительская категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128, unique=True, verbose_name='Модель')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='store.brand', verbose_name='Бренд (Производитель)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='store.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=store.models.vendor.vendor_store_path, verbose_name='Логотип')),
                ('site', models.CharField(max_length=128, verbose_name='Сайт')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('adress', models.CharField(max_length=256, verbose_name='Адрес')),
                ('phone_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Тел.')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Рейтинг')),
                ('review_text', models.TextField(verbose_name='Отзыв')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок отзыва')),
                ('plus', models.TextField(verbose_name='Достоинства')),
                ('minus', models.TextField(verbose_name='Недостатки')),
                ('moderation', models.BooleanField(default=False, verbose_name='Прошел модерацию')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.goods', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoReviewGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to=store.models.product.reviews_image_path, verbose_name=' Фотограция')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='store.reviewgoods')),
            ],
        ),
        migrations.CreateModel(
            name='OfferVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='store.goods', verbose_name='Товар')),
                ('vendors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='store.vendor', verbose_name='Продавец')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.basket')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.goods')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=store.models.product.image_store_path, verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.goods', verbose_name='Товар')),
            ],
        ),
    ]
