# Generated by Django 4.0 on 2022-01-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_pay',
            new_name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='number',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('pickup', 'Самовывоз'), ('courier', 'Курьером')], default='pickup', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='is_deliver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cash', 'Наличными'), ('wallet', 'Кошелек'), ('online', 'online')], default='cash', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('verify', 'Подтверждение'), ('payment', 'Оплата'), ('delivery', 'Доставка'), ('completed', 'Выполнен'), ('cancel', 'Отменен')], default='verify', max_length=16),
        ),
        migrations.AlterField(
            model_name='productinbasket',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
