# Generated by Django 3.2.9 on 2021-12-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='site',
        ),
        migrations.AddField(
            model_name='vendor',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='sug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='slug'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
