# Generated by Django 3.2.9 on 2021-12-26 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211220_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinbasket',
            name='offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='in_baskets', to='store.offervendor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodsinbasket',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_in_basket', to='store.basket'),
        ),
        migrations.AlterField(
            model_name='goodsinbasket',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_baskets', to='store.goods'),
        ),
    ]
