# Generated by Django 3.2.9 on 2021-12-26 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_auto_20211226_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=64, null=True)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('check', 'Подтверждение'), ('payment', 'Оплата'), ('delivery', 'Доставка'), ('ready', 'Готов к выдаче'), ('finish', 'Выполнен'), ('cancel', 'Отменен')], max_length=16)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_pay', models.BooleanField(default=False)),
                ('is_cancel', models.BooleanField(default=False)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.goods', verbose_name='Товар')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name='Заказ')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.vendor', verbose_name='Продавец')),
            ],
        ),
    ]
