# Generated by Django 3.2.9 on 2021-12-26 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_goodsinorder_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='goodsinorder',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.goods', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='goodsinorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='store.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='goodsinorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.vendor', verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('check', 'Подтверждение'), ('payment', 'Оплата'), ('delivery', 'Доставка'), ('ready', 'Готов к выдаче'), ('finish', 'Выполнен'), ('cancel', 'Отменен')], default='check', max_length=16),
        ),
    ]
