# Generated by Django 3.2.9 on 2021-12-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20211226_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offervendor',
            old_name='vendors',
            new_name='vendor',
        ),
        migrations.RemoveField(
            model_name='goodsinbasket',
            name='goods',
        ),
    ]
