version: '3.8'

services:
  main_backend:
    container_name: main_backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 80:8000
    volumes:
      - .:/app
    env_file:
      - .env.prod
    networks:
      - onlinestore_network
    depends_on:
      - main_db

  main_db:
    image: postgres:14.6-alpine
    container_name: main_db
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - onlinestore_network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env.prod

networks:
  onlinestore_network:
    driver: bridge

volumes:
  postgres_data: