# Generated by Django 4.2.2 on 2023-07-20 09:47

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewproduct',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'
            ),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='images',
                to='store.product',
                verbose_name='Товар',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='products',
                to='store.brand',
                verbose_name='Бренд (Производитель)',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='products',
                to='store.category',
                verbose_name='Категория',
            ),
        ),
        migrations.AddField(
            model_name='photoreviewproduct',
            name='review',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='store.reviewproduct'
            ),
        ),
        migrations.AddField(
            model_name='offervendor',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='offers',
                to='store.product',
                verbose_name='Товар',
            ),
        ),
        migrations.AddField(
            model_name='offervendor',
            name='vendor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='offers',
                to='vendors.vendor',
                verbose_name='Продавец',
            ),
        ),
        migrations.AddField(
            model_name='favoriteproduct',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='in_favorites', to='store.product'
            ),
        ),
        migrations.AddField(
            model_name='favoriteproduct',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='favorite_products',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='children',
                to='store.category',
                verbose_name='Родительская категория',
            ),
        ),
    ]
