# Generated by Django 4.2.2 on 2023-07-20 09:47

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.vendors.models.vendor


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                (
                    'logo',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.vendors.models.vendor.vendor_store_path,
                        verbose_name='Логотип',
                    ),
                ),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='sug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewVendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                (
                    'rating',
                    models.PositiveIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Рейтинг'
                    ),
                ),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('moderation', models.BooleanField(default=False, verbose_name='Прешел модерацию')),
                ('create_data', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reviews_vendor',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь',
                    ),
                ),
                (
                    'vendor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reviews',
                        to='vendors.vendor',
                        verbose_name='Продавец',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
