# Generated by Django 4.0 on 2022-01-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_exchangecurrency_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('infected', models.IntegerField()),
                ('death', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('sick', models.IntegerField()),
            ],
        ),
    ]
