# Generated by Django 4.0 on 2022-01-08 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_rename_death_covid_deaths'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='covid',
            options={'ordering': ['-date']},
        ),
    ]
